#ifndef TOURNAMENTBOT_OPERATION_H
#define TOURNAMENTBOT_OPERATION_H

enum Operation{
    DETERMINE_WINNER,
    LOAD_PARTICIPANTS_FROM_FILE,
    CLEAR_DATABASE,
    SORT_INTO_GROUPS,
    POST_RESULT,
    RETRIEVE_GROUP,
    POST_PARTICIPANT,
    RETRIEVE_PARTICIPANTS,
    DELETE_PARTICIPANT,
    DELETE_RESULT,
    SAVE_TO_CSV,
    UNKNOWN_COMMAND
};

#endif
